### ISSUE TITLE
Responsabilidades de la Persistencia

### ISSUE THREAD

**Issue by achani2497** [tomas-aleso/queMePongo#1]
Tengo una duda con respecto a dónde tendrían que estar los metodos Crear / Borrar de la base de datos para cada clase (Evento, Usuario, Guardarropa, etc.). Por ahora en la clase DB lo unico que hay son los metodos consultar"Clase"(){} que trae la cantidad de registros que hay en la DB de esa clase. Vale la pena hacer una clase por cada tabla en la DB en donde esten los metodos que mencioné antes (por ejemplo UsuariosDB) o es mejor utilizar las clases que ya tenemos (ej Usuarios) para meter esos metodos?

**Comment by CDNievas** [comment]
Crei q les habia contestado, existen las clases llamadas DAO que justamente hacen eso, son clases de acceso a datos o manejo de datos que contienen esos métodos. A mi parecer es lo mejor para no mezclar la logica de negocio con la tecnologia

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________
