### ISSUE TITLE
Problema con EF6

### ISSUE THREAD

**Issue by achani2497** [tomas-aleso/queMePongo#2]
No entiendo por qué me tira esta excepcion cuando trato de crear un tipoDePrenda y persistirlo:

`42703: column "Prenda_id_prenda" of relation "tipoprendas" does not exist`

En la tabla prendas tengo un campo que es id_tipoprenda pero en la tabla tipoprendas no tengo un campo que sea id_prenda, es por eso que me tira esa excepcion?

Ejecuta todo sin drama hasta que llega a la ultima linea donde hacemos TipoPrendaRepo.Insert()

<img width="787" alt="Captura de Pantalla 2019-09-28 a la(s) 20 36 45" src="https://user-images.githubusercontent.com/18755423/65823667-f2b88f80-e230-11e9-9534-bfe17038ffa2.png">

**Comment by CDNievas** [comment]
El codigo esta subido? Para verlo

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by achani2497** [comment]
Ahí lo subí

**Comment by CDNievas** [comment]
Ustedes estaban usando Fluent API?

**Comment by achani2497** [comment]
Habiamos empezado a usarlo pero despues lo sacamos

**Comment by CDNievas** [comment]
Entonces si puede ser que sea por eso. Lo que debe pasar es lo siguiente

Ustedes definieron la relación Prenda -> TipoPrenda (Uno a uno)
Pero no definieron la relación TipoPrenda -> Prenda (Uno a muchos)

Se ve que de por si el frame necesita las dos para poder operar correctamente

Si hubieran usado FluentAPI hubiera sido distinto (creo)

Agréguenlo y díganme  si les funciona

**Comment by achani2497** [comment]
Ahi anduvo 👍
